import { Inter } from "next/font/google";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IMKDB",
  description: "Generated by Luka Lekishvili",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ka">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
