import { Inter } from "next/font/google";
import "../styles/globals.scss";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "GIMDB",
  description: "Generated by Luka Lekishvili",
};

export default function RootLayout({ children }) {
  return (
    <SessionProvider session={session}>
      <html lang="ka">
        <body className={inter.className}>{children}</body>
      </html>
    </SessionProvider>
  );
}
